# Generated by Django 2.0.2 on 2018-08-11 15:50

import app.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djongo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devicedata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('healthtype', models.IntegerField(blank=True, default=1, null=True)),
                ('respirations', models.FloatField(blank=True, null=True)),
                ('perfusion', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeviceId', models.CharField(max_length=200)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('sex', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('U', 'Unsure')], max_length=1)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('homeplace', models.CharField(blank=True, max_length=100, null=True)),
                ('livingplace', models.CharField(blank=True, max_length=100, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('hospital', models.CharField(blank=True, max_length=100, null=True)),
                ('datas', djongo.models.ArrayModelField(blank=True, model_container=app.models.Devicedata, model_form_class=app.models.DevicedataForm, null=True)),
                ('inhospital', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', djongo.models.EmbeddedModelField(model_container=app.models.Blog, model_form_class=app.models.BlogForm, null=True)),
                ('headline', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rescue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('commander', models.CharField(max_length=100)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('timestart', models.DateTimeField(default=django.utils.timezone.now)),
                ('timestop', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='devices',
            name='rescue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Rescue'),
        ),
    ]
