# Generated by Django 2.0.2 on 2018-09-12 10:42

import app.models
from django.db import migrations, models
import djongo.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lon', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='routes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=200)),
                ('datas', djongo.models.ArrayModelField(blank=True, model_container=app.models.route, model_form_class=app.models.routeForm, null=True)),
            ],
        ),
    ]
